export const SAVE_JWT_TOKEN="SAVE_JWT_TOKEN";
export const REMOVE_JWT_TOKEN="REMOVE_JWT_TOKEN";
export const SAVE_SITE_INIT_STATE="SAVE_SITE_INIT_STATE";
export const SAVE_MCQ_SEARCH_PARAM="SAVE_MCQ_SEARCH_PARAM";
export const SAVE_TEST_SEARCH_PARAM="SAVE_TEST_SEARCH_PARAM";